# SPDX-FileCopyrightText: 2020 Diego Elio Pettenò
#
# SPDX-License-Identifier: Unlicense

repos:
-   repo: https://github.com/pycqa/pylint
    rev: pylint-2.6.0
    hooks:
    -   id: pylint
        name: lint (examples)
        types: [python]
        files: ^examples/
        args:
        - --disable=missing-docstring,invalid-name,bad-whitespace
    -   id: pylint
        name: lint (code)
        types: [python]
        exclude: "^(docs/|examples/|setup.py$)"
-   repo: https://github.com/python/black
    rev: 20.8b1
    hooks:
    - id: black
-   repo: https://github.com/fsfe/reuse-tool
    rev: v0.12.1
    hooks:
    - id: reuse
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
